name: toko_gaming
description: "Aplikasi Toko Peralatan Gaming (Flutter + PHP API)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking API (PHP Hosting)
  dio: ^5.4.3+1

  # Shared Preferences untuk session login
  shared_preferences: ^2.2.3

  # Icon iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Pastikan kamu punya folder assets/ dan isi minimal 1 gambar:
  # contoh: assets/bg_gaming.jpg
  assets:
    - assets/
